name: circular_menu_example
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  circular_menu:
    path: ../
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  url_launcher: ^6.2.6
  
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
